/// An active session. `token_hash` is BLAKE3(raw_token); raw token is never stored.
#[derive(Debug, Clone)]
pub struct Session {
    pub token_hash: String,
    pub account_id: String,
    pub expires_at: i64,
    pub user_agent: Option<String>,
    pub ip_addr: Option<String>,
    pub created_at: i64,
}

/// Input for creating a new session. The raw token is generated by `SessionRepo::create`.
#[derive(Debug, Clone)]
pub struct NewSession {
    pub account_id: String,
    /// Unix-ms timestamp when this session expires.
    pub expires_at: i64,
    pub user_agent: Option<String>,
    pub ip_addr: Option<String>,
}

/// Opaque raw session token returned to the client (bearer value for cookies/headers).
/// Never stored in the DB — only its BLAKE3 hash is persisted.
#[derive(Debug, Clone)]
pub struct SessionToken(pub String);

impl SessionToken {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
